In [1]:
import numpy as np
import pandas as pd

In [7]:
sales=pd.read_csv(r"C:\Users\Prime\Downloads\archive (9)\ecommerce_sales_customer_analytics_150k.csv")
print(sales)

          order_id  order_date order_time order_status sales_channel  \
0       ORD-301242  2023-11-06   16:37:47    Completed    Mobile App
1       ORD-773460  2025-12-24   01:22:36    Completed       Website
2       ORD-449374  2021-07-05   14:24:21    Completed    Mobile App
3       ORD-567636  2023-01-21   07:20:26    Completed  Social Media
4       ORD-820028  2022-05-13   09:46:21    Completed  Social Media
...            ...         ...        ...          ...           ...
138111  ORD-481534  2025-09-27   13:00:50    Completed    Mobile App
138112  ORD-487614  2023-07-22   09:13:25     Returned  Social Media
138113  ORD-248062  2025-09-08   18:30:32    Cancelled    Mobile App
138114  ORD-252033  2022-04-06   14:50:07    Completed  Social Media
138115  ORD-528577  2022-11-23   11:46:00    Completed    Mobile App

        customer_id     customer_name  customer_age  gender customer_segment  \
0       CUST-003102      Jasmine Ryan            55    Male         Consumer
1       CUST-003124       Scott Chase            26    Male          Premium
2       CUST-012496      Marc Wheeler            69  Female          Premium
3       CUST-023928    Jennifer Smith            65    Male         Consumer
4       CUST-012730      Jessica Wang            34  Female         Consumer
...             ...               ...           ...     ...              ...
138111  CUST-007151        Donna Ruiz            41  Female         Consumer
138112  CUST-006686    Jeremy Aguirre            40    Male          Premium
138113  CUST-017497  Timothy Williams            39  Female         Consumer
138114  CUST-005723    Charles Hanson            46  Female         Consumer
138115  CUST-006809       John Miller            28    Male         Consumer

        ... discount_amount tax_amount shipping_cost net_sales product_cost  \
0       ...          477.89      61.07         12.03    945.40       588.33
1       ...         1456.06     320.83          9.00   2018.41      2031.88
2       ...           97.30      29.79         13.05    468.35       257.73
3       ...           53.34      34.39         20.85    546.52       277.84
4       ...          133.63     421.35         23.03   2785.27      1231.88
...     ...             ...        ...           ...       ...          ...
138111  ...            8.84      14.28          6.15    224.42       101.77
138112  ...            0.00     147.30          9.18   2260.80      1246.73
138113  ...            0.00     372.37         26.94   2261.16       970.95
138114  ...          174.60     130.58         84.39   2080.38      1042.40
138115  ...          417.27     102.26          9.09   1572.22       884.46

         profit profit_margin_percentage customer_lifetime_value  \
0        345.04                    36.50                12459.68
1        -22.47                    -1.11                13032.48
2        197.57                    42.18                 6159.44
3        247.83                    45.35                 5638.30
4       1530.36                    54.94                13240.10
...         ...                      ...                     ...
138111   116.50                    51.91                18182.63
138112  1004.89                    44.45                10004.74
138113  1263.27                    55.87                16442.68
138114   953.59                    45.84                 8047.00
138115   678.67                    43.17                 4107.38

       is_repeat_customer customer_order_count
0                    True                   11
1                    True                   11
2                    True                    6
3                    True                    7
4                    True                    8
...                   ...                  ...
138111               True                   14
138112               True                   10
138113               True                   15
138114               True                    5
138115               True                    5

[138116 rows x 46 columns]

In [8]:
sales.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8

In [10]:
sales.tail()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,...,8.84,14.28,6.15,224.42,101.77,116.50,51.91,18182.63,True,14
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,...,0.00,147.30,9.18,2260.80,1246.73,1004.89,44.45,10004.74,True,10
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,...,0.00,372.37,26.94,2261.16,970.95,1263.27,55.87,16442.68,True,15
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,...,174.60,130.58,84.39,2080.38,1042.40,953.59,45.84,8047.00,True,5
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,...,417.27,102.26,9.09,1572.22,884.46,678.67,43.17,4107.38,True,5

In [11]:
sales.shape

(138116, 46)

In [15]:
sales.columns

Index(['order_id', 'order_date', 'order_time', 'order_status', 'sales_channel',
       'customer_id', 'customer_name', 'customer_age', 'gender',
       'customer_segment', 'customer_type', 'customer_city', 'customer_state',
       'customer_country', 'region', 'customer_postal_code', 'payment_method',
       'payment_status', 'currency', 'shipping_method', 'warehouse',
       'delivery_days', 'estimated_delivery_days', 'delivery_status',
       'return_status', 'return_reason', 'customer_rating', 'review_sentiment',
       'customer_review', 'marketing_channel', 'campaign_name', 'coupon_code',
       'loyalty_points_earned', 'loyalty_points_redeemed', 'quantity',
       'gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost',
       'net_sales', 'product_cost', 'profit', 'profit_margin_percentage',
       'customer_lifetime_value', 'is_repeat_customer',
       'customer_order_count'],
      dtype='str')

In [16]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  str
 1   order_date                138116 non-null  str
 2   order_time                138116 non-null  str
 3   order_status              138116 non-null  str
 4   sales_channel             138116 non-null  str
 5   customer_id               138116 non-null  str
 6   customer_name             138116 non-null  str
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  str
 9   customer_segment          138116 non-null  str
 10  customer_type             138116 non-null  str
 11  customer_city             138116 non-null  str
 12  customer_state            138116 non-null  str
 13  customer_country          138116 non-null  str
 14  region                    138116 non-null  str
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  str
 17  payment_status            138116 non-null  str
 18  currency                  138116 non-null  str
 19  shipping_method           138116 non-null  str
 20  warehouse                 138116 non-null  str
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  str
 24  return_status             9462 non-null    str
 25  return_reason             9462 non-null    str
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  str
 28  customer_review           113559 non-null  str
 29  marketing_channel         138116 non-null  str
 30  campaign_name             54883 non-null   str
 31  coupon_code               27614 non-null   str
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), str(27)
memory usage: 47.6 MB

In [17]:
sales.isnull().sum()

order_id                         0
order_date                       0
order_time                       0
order_status                     0
sales_channel                    0
customer_id                      0
customer_name                    0
customer_age                     0
gender                           0
customer_segment                 0
customer_type                    0
customer_city                    0
customer_state                   0
customer_country                 0
region                           0
customer_postal_code             0
payment_method                   0
payment_status                   0
currency                         0
shipping_method                  0
warehouse                        0
delivery_days                24557
estimated_delivery_days      24557
delivery_status                  0
return_status               128654
return_reason               128654
customer_rating              24557
review_sentiment             24557
customer_review              24557
marketing_channel                0
campaign_name                83233
coupon_code                 110502
loyalty_points_earned            0
loyalty_points_redeemed          0
quantity                         0
gross_sales                      0
discount_amount                  0
tax_amount                       0
shipping_cost                    0
net_sales                        0
product_cost                     0
profit                           0
profit_margin_percentage         0
customer_lifetime_value          0
is_repeat_customer               0
customer_order_count             0
dtype: int64

In [18]:
sales.duplicated().sum()

np.int64(0)

In [19]:
sales.describe()

,customer_age,customer_postal_code,delivery_days,estimated_delivery_days,customer_rating,loyalty_points_earned,loyalty_points_redeemed,quantity,gross_sales,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,customer_order_count
count,138116.000000,138116.000000,113559.000000,113559.000000,113559.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000
mean,45.862681,50210.889310,4.557772,4.298875,3.677015,103.991051,51.934128,5.615244,1375.384176,237.621614,122.462933,22.278080,1282.503575,708.903449,551.322046,45.065997,8971.639047,6.990559
std,16.467676,28569.767779,2.810012,2.594080,0.483672,115.175640,73.217692,3.371289,1291.009554,378.779459,140.939368,16.022739,1169.274669,730.044970,516.300936,13.120357,4430.506588,2.444166
min,18.000000,516.000000,0.000000,0.000000,1.600000,0.000000,0.000000,1.000000,6.310000,0.000000,0.340000,0.000000,5.800000,1.970000,-1281.590000,-59.550000,22.550000,1.000000
25%,32.000000,25509.000000,2.000000,2.000000,3.400000,17.000000,3.000000,3.000000,458.920000,26.327500,34.650000,9.820000,448.200000,207.667500,190.757500,38.880000,5713.570000,5.000000
50%,46.000000,50183.000000,4.000000,4.000000,3.700000,70.000000,25.000000,5.000000,995.730000,103.285000,77.010000,19.190000,950.760000,478.955000,408.395000,46.990000,8392.525000,7.000000
75%,60.000000,74898.000000,7.000000,6.000000,4.000000,151.000000,71.000000,8.000000,1871.200000,277.125000,156.200000,30.750000,1744.582500,953.762500,752.845000,53.770000,11651.030000,9.000000
max,74.000000,99950.000000,14.000000,10.000000,5.000000,1621.000000,1063.000000,24.000000,16051.190000,6759.020000,2091.520000,149.520000,16218.000000,9963.410000,7083.680000,77.590000,30268.440000,20.000000

In [20]:
sales["order_status"].value_counts()

order_status
Completed    113559
Returned       9462
Cancelled      8398
Pending        6697
Name: count, dtype: int64

In [21]:
sales["customer_segment"].value_counts()

customer_segment
Consumer    75636
Premium     34746
VIP         13957
Business    13777
Name: count, dtype: int64

In [23]:
sales.nunique()

order_id                    138116
order_date                    1826
order_time                   68991
order_status                     4
sales_channel                    4
customer_id                  24911
customer_name                21564
customer_age                    57
gender                           3
customer_segment                 4
customer_type                    3
customer_city                15516
customer_state                  38
customer_country                 7
region                           5
customer_postal_code         22117
payment_method                   7
payment_status                   4
currency                         7
shipping_method                  4
warehouse                       19
delivery_days                   15
estimated_delivery_days         11
delivery_status                  4
return_status                    1
return_reason                    8
customer_rating                 35
review_sentiment                 3
customer_review                 25
marketing_channel               10
campaign_name                   17
coupon_code                     40
loyalty_points_earned          846
loyalty_points_redeemed        642
quantity                        24
gross_sales                 100130
discount_amount              58437
tax_amount                   43093
shipping_cost                11973
net_sales                   112204
product_cost                 88450
profit                       91021
profit_margin_percentage      7947
customer_lifetime_value      24752
is_repeat_customer               2
customer_order_count            19
dtype: int64

In [24]:
sales["order_date"] = pd.to_datetime(sales["order_date"])

In [28]:
sales["order_date"].dtype

dtype('<M8[us]')

In [29]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  str
 1   order_date                138116 non-null  datetime64[us]
 2   order_time                138116 non-null  str
 3   order_status              138116 non-null  str
 4   sales_channel             138116 non-null  str
 5   customer_id               138116 non-null  str
 6   customer_name             138116 non-null  str
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  str
 9   customer_segment          138116 non-null  str
 10  customer_type             138116 non-null  str
 11  customer_city             138116 non-null  str
 12  customer_state            138116 non-null  str
 13  customer_country          138116 non-null  str
 14  region                    138116 non-null  str
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  str
 17  payment_status            138116 non-null  str
 18  currency                  138116 non-null  str
 19  shipping_method           138116 non-null  str
 20  warehouse                 138116 non-null  str
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  str
 24  return_status             9462 non-null    str
 25  return_reason             9462 non-null    str
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  str
 28  customer_review           113559 non-null  str
 29  marketing_channel         138116 non-null  str
 30  campaign_name             54883 non-null   str
 31  coupon_code               27614 non-null   str
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), datetime64[us](1), float64(12), int64(6), str(26)
memory usage: 47.6 MB

In [34]:
sales["gender"].unique()

<StringArray>
['Male', 'Female', 'Non-Binary']
Length: 3, dtype: str

In [35]:
sales["customer_segment"].unique()

<StringArray>
['Consumer', 'Premium', 'VIP', 'Business']
Length: 4, dtype: str

In [36]:
sales["customer_segment"].value_counts ()

customer_segment
Consumer    75636
Premium     34746
VIP         13957
Business    13777
Name: count, dtype: int64

In [37]:
missing = sales.isnull().sum().sort_values(ascending=True)
missing = missing[missing > 0]

In [38]:
print(missing)

delivery_days               24557
review_sentiment            24557
estimated_delivery_days     24557
customer_rating             24557
customer_review             24557
campaign_name               83233
coupon_code                110502
return_reason              128654
return_status              128654
dtype: int64

In [39]:
sales["return_status"].value_counts(dropna=False)

return_status
NaN         128654
Returned      9462
Name: count, dtype: int64

In [40]:
sales[sales["customer_rating"].isnull()]["review_sentiment"].value_counts(dropna=False)

review_sentiment
NaN    24557
Name: count, dtype: int64

In [41]:
sales[sales["delivery_days"].isnull()]["delivery_status"].value_counts(dropna=False)

delivery_status
Cancelled    24557
Name: count, dtype: int64

In [42]:
sales["customer_rating"].isnull().sum()

np.int64(24557)

In [43]:
sales["review_sentiment"].value_counts(dropna=False)

review_sentiment
Positive    78083
Neutral     34684
NaN         24557
Negative      792
Name: count, dtype: int64

In [44]:
sales["review_sentiment"] = sales["review_sentiment"].fillna("No Review")

In [45]:
sales["customer_review"] = sales["customer_review"].fillna("No Review")

In [46]:
sales["campaign_name"] = sales["campaign_name"].fillna("No Campaign")

In [47]:
sales["coupon_code"] = sales["coupon_code"].fillna("No Coupon")

In [48]:
sales["return_status"] = sales["return_status"].fillna("Not Returned")
sales["return_reason"] = sales["return_reason"].fillna("Not Returned")

In [49]:
missing = sales.isnull().sum().sort_values(ascending=True)
missing = missing[missing > 0]

In [50]:
print(missing)

delivery_days              24557
customer_rating            24557
estimated_delivery_days    24557
dtype: int64

In [51]:
sales[sales["delivery_days"].isnull()]["delivery_status"].value_counts(dropna=False)

delivery_status
Cancelled    24557
Name: count, dtype: int64

In [52]:
sales.columns

Index(['order_id', 'order_date', 'order_time', 'order_status', 'sales_channel',
       'customer_id', 'customer_name', 'customer_age', 'gender',
       'customer_segment', 'customer_type', 'customer_city', 'customer_state',
       'customer_country', 'region', 'customer_postal_code', 'payment_method',
       'payment_status', 'currency', 'shipping_method', 'warehouse',
       'delivery_days', 'estimated_delivery_days', 'delivery_status',
       'return_status', 'return_reason', 'customer_rating', 'review_sentiment',
       'customer_review', 'marketing_channel', 'campaign_name', 'coupon_code',
       'loyalty_points_earned', 'loyalty_points_redeemed', 'quantity',
       'gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost',
       'net_sales', 'product_cost', 'profit', 'profit_margin_percentage',
       'customer_lifetime_value', 'is_repeat_customer',
       'customer_order_count'],
      dtype='str')

In [53]:
sales.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8

In [54]:
sales["currency"].value_counts()

currency
USD    82600
GBP    20235
EUR    11593
CAD     7015
AUD     6794
INR     5707
AED     4172
Name: count, dtype: int64

In [55]:
sales["order_year"]=sales["order_date"].dt.year

In [56]:
sales["order_year"].head()

0    2023
1    2025
2    2021
3    2023
4    2022
Name: order_year, dtype: int32

In [57]:
sales["order_month"]=sales["order_date"].dt.month

In [58]:
sales["order_month"].head()

0    11
1    12
2     7
3     1
4     5
Name: order_month, dtype: int32

In [59]:
sales["discount_percentage"]= (sales["discount_amount"] / sales["gross_sales"] * 100)

In [60]:
sales["discount_percentage"].head()

0    35.394278
1    46.302915
2    18.610968
3     9.793985
4     5.400239
Name: discount_percentage, dtype: float64

In [61]:
sales["delivery_difference"] = (sales["delivery_days"] - sales["estimated_delivery_days"])

In [63]:
sales["delivery_difference"].head(10)

0    0.0
1    0.0
2    0.0
3    0.0
4    1.0
5    NaN
6    4.0
7    0.0
8    0.0
9    0.0
Name: delivery_difference, dtype: float64

In [65]:
sales["delivery_performance"] = sales["delivery_difference"].apply(lambda x: "Late" if x >0 else "Early" if x < 0 else "On Time")

In [66]:
sales["delivery_performance"].head()

0    On Time
1    On Time
2    On Time
3    On Time
4       Late
Name: delivery_performance, dtype: str

In [67]:
sales.shape

(138116, 51)

In [68]:
order=pd.read_csv(r"C:\Users\Prime\Downloads\archive (9)\order_items.csv")

In [70]:
order.head()

,order_id,product_id,quantity,unit_price,discount_percentage,discount_amount,gross_sales,tax_amount,shipping_cost,net_sales,product_cost,profit
0,ORD-301242,PROD-000738,2,244.40,0.339607,166.00,488.80,22.60,6.48,351.88,173.28,172.12
1,ORD-301242,PROD-000181,3,287.13,0.362076,311.89,861.39,38.47,5.55,593.52,415.05,172.92
2,ORD-773460,PROD-000973,4,754.80,0.468300,1413.89,3019.20,305.01,9.00,1919.32,1976.16,-65.84
3,ORD-773460,PROD-000268,4,31.36,0.336182,42.17,125.44,15.82,0.00,99.09,55.72,43.37
4,ORD-449374,PROD-001040,3,6.31,0.089678,1.70,18.93,1.21,0.98,19.42,5.91,12.53

In [73]:
order.tail()

,order_id,product_id,quantity,unit_price,discount_percentage,discount_amount,gross_sales,tax_amount,shipping_cost,net_sales,product_cost,profit
397564,ORD-252033,PROD-000792,2,137.53,0.156007,42.91,275.06,16.25,6.21,254.61,142.54,105.86
397565,ORD-252033,PROD-000804,5,118.96,0.097011,57.70,594.80,37.60,14.89,589.59,280.80,293.90
397566,ORD-252033,PROD-000527,3,52.50,0.141821,22.34,157.50,9.46,23.86,168.48,64.47,80.15
397567,ORD-528577,PROD-000004,1,1120.49,0.075121,84.17,1120.49,72.54,3.33,1112.19,564.86,544.00
397568,ORD-528577,PROD-000357,5,151.53,0.439653,333.10,757.65,29.72,5.76,460.03,319.60,134.67

In [74]:
order.shape

(397569, 12)

In [76]:
order.columns

Index(['order_id', 'product_id', 'quantity', 'unit_price',
       'discount_percentage', 'discount_amount', 'gross_sales', 'tax_amount',
       'shipping_cost', 'net_sales', 'product_cost', 'profit'],
      dtype='str')

In [77]:
order.info()

<class 'pandas.DataFrame'>
RangeIndex: 397569 entries, 0 to 397568
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             397569 non-null  str
 1   product_id           397569 non-null  str
 2   quantity             397569 non-null  int64
 3   unit_price           397569 non-null  float64
 4   discount_percentage  397569 non-null  float64
 5   discount_amount      397569 non-null  float64
 6   gross_sales          397569 non-null  float64
 7   tax_amount           397569 non-null  float64
 8   shipping_cost        397569 non-null  float64
 9   net_sales            397569 non-null  float64
 10  product_cost         397569 non-null  float64
 11  profit               397569 non-null  float64
dtypes: float64(9), int64(1), str(2)
memory usage: 36.4 MB

In [78]:
order.describe()

,quantity,unit_price,discount_percentage,discount_amount,gross_sales,tax_amount,shipping_cost,net_sales,product_cost,profit
count,397569.000000,397569.000000,397569.000000,397569.000000,397569.000000,397569.000000,397569.000000,397569.000000,397569.000000,397569.000000
mean,2.118792,245.189134,0.147059,89.667873,519.013550,46.183642,8.409010,483.938328,267.520046,208.009273
std,1.196276,251.035134,0.129986,190.637796,676.800478,71.072019,6.777155,615.430188,394.773555,266.477677
min,1.000000,6.310000,0.000000,0.000000,6.310000,0.260000,0.000000,5.350000,1.970000,-1260.280000
25%,1.000000,74.360000,0.048137,5.940000,122.000000,9.560000,3.370000,124.280000,52.960000,53.730000
50%,2.000000,164.970000,0.124253,26.340000,280.190000,22.550000,5.870000,271.100000,127.100000,121.660000
75%,3.000000,310.790000,0.199499,86.030000,643.560000,52.340000,12.460000,595.240000,314.310000,259.660000
max,5.000000,1482.950000,0.600000,3857.670000,7414.750000,1482.950000,36.460000,8897.700000,4968.150000,4045.100000

In [79]:
order.duplicated().sum()

np.int64(0)

In [82]:
missing=order.isnull().sum().sort_values(ascending=True)
missing=missing[missing>0]

In [83]:
print(missing)

Series([], dtype: int64)

In [84]:
order.isnull().sum()

order_id               0
product_id             0
quantity               0
unit_price             0
discount_percentage    0
discount_amount        0
gross_sales            0
tax_amount             0
shipping_cost          0
net_sales              0
product_cost           0
profit                 0
dtype: int64

In [87]:
order["sales_per_unit"] = (order["net_sales"] / order["quantity"])

In [88]:
order["sales_per_unit"].head()

0    175.940000
1    197.840000
2    479.830000
3     24.772500
4      6.473333
Name: sales_per_unit, dtype: float64

In [89]:
order["profit_per_unit"] = (order["profit"] / order["quantity"])

In [90]:
order["profit_per_unit"].head()

0    86.060000
1    57.640000
2   -16.460000
3    10.842500
4     4.176667
Name: profit_per_unit, dtype: float64

In [93]:
product=pd.read_csv(r"C:\Users\Prime\Downloads\archive (9)\product_catalog.csv")

In [94]:
product.head()

,product_id,product_name,product_category,product_subcategory,brand,supplier,unit_price,product_cost,product_rating
0,PROD-000001,Apple Sharable bifurcated algorithm Smartphones,Electronics,Smartphones,Apple,Alibaba,686.90,474.06,4.3
1,PROD-000002,Google User-centric even-keeled encryption Sma...,Electronics,Smartphones,Google,Euro Logistics,978.26,519.66,2.9
2,PROD-000003,LG Face-to-face client-driven support Smartphones,Electronics,Smartphones,LG,Asian Manufacturing,275.51,185.48,3.9
3,PROD-000004,Sony Customer-focused systematic support Smart...,Electronics,Smartphones,Sony,Amazon Supply,1120.49,564.86,4.8
4,PROD-000005,OnePlus Quality-focused background parallelism...,Electronics,Smartphones,OnePlus,Direct Import,1282.18,695.54,2.9

In [95]:
product.shape

(1175, 9)

In [96]:
product.info()

<class 'pandas.DataFrame'>
RangeIndex: 1175 entries, 0 to 1174
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1175 non-null   str
 1   product_name         1175 non-null   str
 2   product_category     1175 non-null   str
 3   product_subcategory  1175 non-null   str
 4   brand                1175 non-null   str
 5   supplier             1175 non-null   str
 6   unit_price           1175 non-null   float64
 7   product_cost         1175 non-null   float64
 8   product_rating       1175 non-null   float64
dtypes: float64(3), str(6)
memory usage: 82.7 KB

In [97]:
product.duplicated().sum()

np.int64(0)

In [98]:
product.isnull().sum()

product_id             0
product_name           0
product_category       0
product_subcategory    0
brand                  0
supplier               0
unit_price             0
product_cost           0
product_rating         0
dtype: int64

In [99]:
product.describe()

        unit_price  product_cost  product_rating
count  1175.000000   1175.000000     1175.000000
mean    245.524400    126.536826        3.683064
std     251.267683    150.131833        0.698046
min       6.310000      1.970000        2.500000
25%      74.710000     29.565000        3.100000
50%     165.420000     74.540000        3.700000
75%     311.295000    153.045000        4.300000
max    1482.950000    993.630000        4.900000

In [100]:
customer=pd.read_csv(r"C:\Users\Prime\Downloads\archive (9)\customer_master.csv")

In [101]:
customer.head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

In [102]:
customer.shape

(25000, 11)

In [103]:
customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                25000 non-null  str
 1   customer_name              25000 non-null  str
 2   customer_age               25000 non-null  int64
 3   gender                     25000 non-null  str
 4   customer_segment           25000 non-null  str
 5   customer_city              25000 non-null  str
 6   customer_state             25000 non-null  str
 7   customer_country           25000 non-null  str
 8   region                     25000 non-null  str
 9   customer_postal_code       25000 non-null  int64
 10  customer_acquisition_cost  25000 non-null  float64
dtypes: float64(1), int64(2), str(8)
memory usage: 2.1 MB

In [104]:
customer.duplicated().sum()

np.int64(0)

In [105]:
sales.shape

(138116, 51)

In [106]:
order.shape

(397569, 14)

In [107]:
product.shape

(1175, 9)

In [108]:
customer.shape

(25000, 11)

In [113]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

username = "root"
password = "Shankru@123"
host = "localhost"
port = 3306
database = "ecommercedb"

connection_url = URL.create(
    drivername="mysql+pymysql",
    username=username,
    password=password,
    host=host,
    port=port,
    database=database
)

engine = create_engine(connection_url)

In [115]:
sales.shape

(138116, 51)

In [116]:
sales.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count,order_year,order_month,discount_percentage,delivery_difference,delivery_performance
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,345.04,36.50,12459.68,True,11,2023,11,35.394278,0.0,On Time
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,-22.47,-1.11,13032.48,True,11,2025,12,46.302915,0.0,On Time
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,197.57,42.18,6159.44,True,6,2021,7,18.610968,0.0,On Time
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,247.83,45.35,5638.30,True,7,2023,1,9.793985,0.0,On Time
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,1530.36,54.94,13240.10,True,8,2022,5,5.400239,1.0,Late

In [117]:
sales.tail()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count,order_year,order_month,discount_percentage,delivery_difference,delivery_performance
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,...,116.50,51.91,18182.63,True,14,2025,9,4.153550,0.0,On Time
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,...,1004.89,44.45,10004.74,True,10,2023,7,0.000000,NaN,On Time
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,...,1263.27,55.87,16442.68,True,15,2025,9,0.000000,NaN,On Time
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,...,953.59,45.84,8047.00,True,5,2022,4,8.558782,1.0,Late
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,...,678.67,43.17,4107.38,True,5,2022,11,22.217194,0.0,On Time

In [120]:
sales.to_sql(
    "sales",
    engine,
    if_exists="replace",
    index=False
)

138116

In [122]:
result = pd.read_sql("SELECT COUNT(*) AS total_rows FROM sales;", engine)

In [123]:
order.to_sql("order", engine, if_exists="replace", index=False)

product.to_sql("product", engine, if_exists="replace", index=False)

customer.to_sql("customer", engine, if_exists="replace", index=False)

25000